spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/laundry_service
    username: postgres
    password: priyansh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: priyansh2v@gmail.com
    password: ndnuicenmmdmgeyy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: kYTpUQ8Pcc3LmYD13+p4OZnBvG1hCDuq8BpClv+NU0isbpjPwxSPhbu5FpBqNoEZ
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088
